### ISSUE TITLE
xml-stylesheet processing instruction in the test-models

### ISSUE THREAD

**Issue by dewancse** [cellml/cellml1to2#5]
Hi all,

IMHO, I am using a cohort of CellML models which are 1.0/1.1 and these models do not have href line like here: https://github.com/cellml/cellml1to2/blob/master/test-models/cellml1.0.xml#L2. But if I remove that href line and convert CellML 1.0/1.1 to 2.0, I don't get any error. IMHO, what is the purpose of href line?

Thanks,
Dewan

**Comment by nickerso** [comment]
Just to clarify, I think this is more about what that `<?xml-stylesheet...?>` does and whether it should be in the test files.

**Comment by hsorby** [comment]
I think it links the XSL Style Sheet to the XML Document. If you were to load this in a XSLT compliant browser it should apply the transform and display that. https://www.w3schools.com/xml/xsl_transformation.asp.
